window.PT_CATALOG = {
  "sm-basic": { name: "Social media page — Basic", price: 25, kind: "Marketing" },
  "sm-standard": { name: "Social media page — Standard", price: 40, kind: "Marketing" },
  "sm-premium": { name: "Social media page — Premium", price: 55, kind: "Marketing" },
  "blog-basic": { name: "Blog — Basic", price: 40, kind: "Marketing" },
  "blog-standard": { name: "Blog — Standard", price: 60, kind: "Marketing" },
  "blog-premium": { name: "Blog — Premium", price: 75, kind: "Marketing" },
  "static-basic": { name: "Static website — Basic", price: 80, kind: "Website" },
  "static-standard": { name: "Static website — Standard", price: 140, kind: "Website" },
  "static-premium": { name: "Static website — Premium", price: 180, kind: "Website" },
  "dyn-basic": { name: "Dynamic website — Basic", price: 120, kind: "Website" },
  "dyn-standard": { name: "Dynamic website — Standard", price: 200, kind: "Website" },
  "dyn-premium": { name: "Dynamic website — Premium", price: 280, kind: "Website" },
  "app-basic": { name: "Web application — Basic", price: 180, kind: "Website" },
  "app-standard": { name: "Web application — Standard", price: 280, kind: "Website" },
  "app-premium": { name: "Web application — Premium", price: 400, kind: "Website" },
  "wp-basic": { name: "Website — Basic", price: 120, kind: "Website" },
  "wp-standard": { name: "Website — Standard", price: 200, kind: "Website" },
  "wp-premium": { name: "Website — Premium", price: 280, kind: "Website" },
  "shop-basic": { name: "Shopify store — Basic", price: 160, kind: "Website" },
  "shop-standard": { name: "Shopify store — Standard", price: 250, kind: "Website" },
  "shop-premium": { name: "Shopify store — Premium", price: 360, kind: "Website" },
  "eco-basic": { name: "Ecommerce website — Basic", price: 220, kind: "Website" },
  "eco-standard": { name: "Ecommerce website — Standard", price: 320, kind: "Website" },
  "eco-premium": { name: "Ecommerce website — Premium", price: 420, kind: "Website" },
  "logo-basic": { name: "Logo — Basic", price: 20, kind: "Graphic" },
  "logo-standard": { name: "Logo — Standard", price: 32, kind: "Graphic" },
  "logo-premium": { name: "Logo — Premium", price: 40, kind: "Graphic" },
  "card-basic": { name: "Business card — Basic", price: 10, kind: "Graphic" },
  "card-standard": { name: "Business card — Standard", price: 15, kind: "Graphic" },
  "card-premium": { name: "Business card — Premium", price: 20, kind: "Graphic" },
  "flyer-basic": { name: "Flyer — Basic", price: 15, kind: "Graphic" },
  "flyer-standard": { name: "Flyer — Standard", price: 22, kind: "Graphic" },
  "flyer-premium": { name: "Flyer — Premium", price: 30, kind: "Graphic" },
  "box-basic": { name: "Business in a box — Basic", price: 60, kind: "Graphic" },
  "box-standard": { name: "Business in a box — Standard", price: 85, kind: "Graphic" },
  "box-premium": { name: "Business in a box — Premium", price: 110, kind: "Graphic" },
  "mkt-social": { name: "Social media marketing (monthly)", price: 80, kind: "Marketing" },
  "mkt-seo": { name: "SEO — 1 month", price: 150, kind: "Marketing" },
  "mkt-ppc": { name: "PPC management (monthly)", price: 90, kind: "Marketing" },
  "mkt-content": { name: "Content marketing (monthly)", price: 70, kind: "Marketing" },
  "mkt-rank": { name: "Google ranking work — 1 month", price: 150, kind: "Marketing" },
  "mkt-email": { name: "Email marketing setup", price: 55, kind: "Marketing" },
  "pos": { name: "Retail POS system", price: 270, kind: "Software" },
  "restaurant-pos": { name: "Restaurant POS", price: 270, kind: "Software" },
  "school-sys": { name: "School management system", price: 270, kind: "Software" },
  "clinic": { name: "Clinic records", price: 270, kind: "Software" },
  "momo": { name: "Mobile Money integration", price: 55, kind: "Software" }
};
