[PHP]
short_open_tag = On
error_reporting = E_ALL
display_errors = On
log_errors = On
extension_dir = C:\Program Files\php-8.4.14-Win32-vs17-x64\ext
extension = php_pdo_mysql.dll
extension = php_mysqli.dll
extension = php_curl.dll
extension = php_openssl.dll
date.timezone = Africa/Kampala
